name: Continuous Integration

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop

jobs:
    build:
        name: Run end-to-end tests and build Docker image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code from GitHub
              uses: actions/checkout@v3

            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: "3.10"

            - name: Install poetry
              run: |
                python -m pip install poetry==1.7.0

            - name: Configure poetry
              run: |
                python -m poetry config virtualenvs.in-project true

            - name: Cache the virtualenv
              uses: actions/cache@v3
              with:
                path: ./.venv
                key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
          
            - name: Install dependencies
              run: |
                python -m poetry install

            - name: Test with pytest
              run: |
                python -m poetry run pytest